title: "Dr Naresh Sampara"
author: "Naresh Sampara"
description: "University of Nottingham"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

url: https://naresh198457.github.io # the base hostname & protocol for your site
baseurl: /DrSampara/blog/

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "CV.md",title: "CV"}
  - {file: "README.md",title: "Research Projects"}
  - {title: "Blog", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:naresh.sampara@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/naresh198457"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
